name: mobx_codegen
description: Code generator for MobX that adds support for annotating your code with @observable, @computed, @action and also creating Store classes.
version: 2.0.1+3

homepage: https://github.com/mobxjs/mobx.dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  analyzer: ^1.7.1
  build: ^2.0.2
  meta: ^1.3.0
  mobx: ^2.0.1
  source_gen: ^1.0.2

dev_dependencies:
  build_runner: ^2.0.4
